# Site settings
title: hyeonghoonpark
email: hyeonghoonpark@gmail.com
name : hyeonghoonpark
description: > # this means to ignore newlines until "baseurl:"
  Refactoring
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hyeonghoonpark.github.io" # the base hostname & protocol for your site
github_username:  hyeonghoonpark
highlighter: pygments
markdown : redcarpet

# Build settings
# markdown: kramdown

# dbyll setting
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude

description: Refactoring
author:
  name: hyeonghoonpark
  email: hyeonghoonpark@gmail.com
  github: hyeonghoonpark
  bio: Refactoring34
  email_md5: 111

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
# end dbyll setting

# Prose
prose:
  media: 'assets/media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          label: "Title"
          element: "text"
      - name: "date"
        field:
          label: "Date"
          element: "text"
      - name: "category"
        field:
          label: "Category"
          element: "text"

# guard
destination: ./public
exclude: ['scss','Gem*','Guard*','*.rb','.sass-cache','.git']
